# Generated by Django 6.0.3 on 2026-04-07 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_medicine_dosage_alter_medicine_prescribed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicine',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Adherence',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
