# Generated by Django 6.0.3 on 2026-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pillevent_medicine_id_pillevent_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillevent',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='pillevent',
            name='patient',
        ),
        migrations.AddField(
            model_name='pillevent',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pillevent',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
