# Generated by Django 6.0.3 on 2026-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile_address_profile_age_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='prescription_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='prescription_image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
